version: "3"

services:
  cassandra:
    image: cassandra:latest
    container_name: user-cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    hostname: qsearchmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq_go_net

volumes:
  cassandra-data:
  rabbitmq-data:

networks:
  rabbitmq_go_net:
    driver: bridge
